project:
  type: website
  output-dir: docs

  

website:
  title: "Aashish Gupta"
  navbar:
    search: false
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
      - href: index.qmd
        text: Home
      - href: https://lekhajokha.github.io/blog/
        text: Blog

      
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

